### ISSUE TITLE
Codecov 4. update

### ISSUE THREAD

**Issue by PierreMartinon** [control-toolbox/CTDirect.jl#102]
Codecov 4. is a breaking release, with uploads now requiring authentication tokens (apparently we can use organization tokens, so one for the whole control-toolbox may more simple than one for every package)

Trying to update on CTDirect, currently a few problems
- key does not have a trusted signature or whatever that means 
```
gpg: Good signature from "Codecov Uploader (Codecov Uploader Verification Key) <security@codecov.io>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
```
- more annoying, codecov complains about unusable coverage report uploaded, which may be linked to the 'code: null' part in the CI report
```
info - 2024-05-31 10:16:43,216 -- Process Report creating complete
info - 2024-05-31 10:16:43,217 -- Finished creating report successfully --- {"response": "{\"external_id\":\"a4889894-532c-4d24-b6b4-4f8a2242cf0a\",\"created_at\":\"2024-05-24T15:43:50.926086Z\",\"commit_sha\":\"60edc0c8be071bba860db12c768f46f29e482592\",\"code\":null}"}
```

**Comment by PierreMartinon** [comment]
Ok, a step was missing. The following works:
```
jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@latest
      - uses: julia-actions/add-julia-registry@v1
        with:
          key: ${{ secrets.SSH_KEY }}
          registry: control-toolbox/ct-registry
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```
